import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="w-full min-h-[100vh] flex flex-col items-center justify-start font-roboto">
        <header className="py-4 h-[50px] w-full text-center bg-blue-950 text-lime-100">
          Welcome to the Car Dealer App
        </header>
        {children}
        <footer className="h-[50px] w-full bg-blue-950 flex items-center justify-center gap-1 text-lime-100">
          Developed by{' '}
          <a href="https://www.linkedin.com/in/julianllop/" target="_blank" className="text-blue-300 ">
            Julian Llop
          </a>
        </footer>
      </body>
    </html>
  );
}
